#!/bin/tcsh -f
# usage: trewrapper framebins filename [dirs]

# set arguments
@ framebins = $1
set basename = $2

@ nargs = $#argv
if ( $nargs > 2 ) then
    # if there are more arguments, loop over them instead of looping over
    # directories in local directory
    set dirs = ($argv[3-$nargs])
    # get current directory
    set thisDir = `pwd`
    foreach i ($dirs)
		cd $i
		echo 'hostname; unset DISPLAY; cd $PBS_O_WORKDIR;'"hostname > treout${framebins}; /ccb/home/syen/matlab/Cat/bin/treCompute $framebins ${basename} >> treout${framebins} 2>&1" | qsub -V -l nodes=1 -j oe -o $PWD/qsubTRE${framebins} -N trecompute -
		cd $thisDir
    end
else
    set dirs = (`ls -d [a-z][1-9]`)
    foreach i ($dirs)
		cd $i
		foreach j (*)
			cd $j
			foreach k (*)
				cd $k
				echo 'hostname; unset DISPLAY; cd $PBS_O_WORKDIR;'"hostname > treout${framebins}; /ccb/home/syen/matlab/Cat/bin/treCompute $framebins ${basename} >> treout${framebins} 2>&1" | qsub -V -l nodes=1 -j oe -o $PWD/qsubTRE${framebins} -N trecompute -
				cd ..
			end
			cd ..
		end
		cd ..
    end
endif
