function test(obj)

shufflesync('auto','RedoDataFile','RecalcData');
shufflesync('auto','RecalcData','SurrData','shsys2data.mat','SurrFilePrefix','shsy2surr','ResultFile','shsy2result.mat');
shufflesync('auto','RecalcData','Shuffle',4,'SurrData','shsys2dataA.mat','SurrFilePrefix','shsy2surrA','ResultFile','shsy2resultA.mat');
shufflesync('auto','RecalcData','Shuffle',6,'SurrData','shsys2dataB.mat','SurrFilePrefix','shsy2surrB','ResultFile','shsy2resultB.mat');
shufflesync('auto','RecalcData','Shuffle',8,'SurrData','shsys2dataC.mat','SurrFilePrefix','shsy2surrC','ResultFile','shsy2resultC.mat');

% regenerate shsy2sdata
[ndintra,sh] = ProcessDirs(ndintra,'Object','shufflesync','DataFile','shsy2data.mat', ...
    'SurrData','shsy2sdata.mat','SurrFilePrefix','shsy2surr','ResultFile','shsy2result.mat','RecalcData');
[ndintra,sh] = ProcessDirs(ndintra,'Object','shufflesync','DataFile','shsy2data.mat', ...
    'SurrData','shsy2sdataA.mat','SurrFilePrefix','shsy2surrA','ResultFile','shsy2resultA.mat','RecalcData','Shuffle',4);
[ndintra,sh] = ProcessDirs(ndintra,'Object','shufflesync','DataFile','shsy2data.mat', ...
    'SurrData','shsy2sdataB.mat','SurrFilePrefix','shsy2surrB','ResultFile','shsy2resultB.mat','RecalcData','Shuffle',6);
[ndintra,sh] = ProcessDirs(ndintra,'Object','shufflesync','DataFile','shsy2data.mat', ...
    'SurrData','shsy2sdataC.mat','SurrFilePrefix','shsy2surrC','ResultFile','shsy2resultC.mat','RecalcData','Shuffle',8);

[ndinter,sh] = ProcessDirs(ndinter,'Object','shufflesync','DataFile','shsy2data.mat', ...
    'SurrData','shsy2sdata.mat','SurrFilePrefix','shsy2surr','ResultFile','shsy2result.mat','RecalcData');
[ndinter,sh] = ProcessDirs(ndinter,'Object','shufflesync','DataFile','shsy2data.mat', ...
    'SurrData','shsy2sdataA.mat','SurrFilePrefix','shsy2surrA','ResultFile','shsy2resultA.mat','RecalcData','Shuffle',4);
[ndinter,sh] = ProcessDirs(ndinter,'Object','shufflesync','DataFile','shsy2data.mat', ...
    'SurrData','shsy2sdataB.mat','SurrFilePrefix','shsy2surrB','ResultFile','shsy2resultB.mat','RecalcData','Shuffle',6);
[ndinter,sh] = ProcessDirs(ndinter,'Object','shufflesync','DataFile','shsy2data.mat', ...
    'SurrData','shsy2sdataC.mat','SurrFilePrefix','shsy2surrC','ResultFile','shsy2resultC.mat','RecalcData','Shuffle',8);

for i in $( cat intrapairs.txt interpairs.txt ); do cd $i; mlqsub "shufflesync('auto','RecalcData','RedoDataFile','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surr','ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat');shufflesync('auto','RecalcData','Shuffle',4,'DataFile','shsy2data.mat','SurrData','shsy2sdataA.mat','SurrFilePrefix','shsy2surrA','ResultFile','shsy2resultA.mat');shufflesync('auto','RecalcData','Shuffle',6,'DataFile','shsy2data.mat','SurrData','shsy2sdataB.mat','SurrFilePrefix','shsy2surrB','ResultFile','shsy2resultB.mat');shufflesync('auto','RecalcData','Shuffle',8,'DataFile','shsy2data.mat','SurrData','shsy2sdataC.mat','SurrFilePrefix','shsy2surrC','ResultFile','shsy2resultC.mat');"; cd -; done

shsywrapper 1700 100 shsysdata; shsywrapper 1700 100 shsysdataA; shsywrapper 1700 100 shsysdataB; shsywrapper 1700 100 shsysdataC;

shsynodelaunch

nframes=( $(cat pf.txt | cut -f 2 -d " ") )
index=0
for dname in $( cat intrapairs.txt interpairs.txt ); do
	cd $dname;
	for j in "" A B C; do
		echo "shsywrapper ${nframes[$index]} 100 shsy2sdata${j}.mat";
	done;
	cd -;
	let "index+=1";
done;

% commands to compute mean and std of truncated normal distribution
% will need Matlab7
pdf_truncnorm = @(x,mu,sigma) normpdf(x,mu,sigma) ./ (1-normcdf(0,mu,sigma));
for lagi = lagsvec
    testdata = full(xcsdata(:,lagi));
    if(sum(testdata)>0)
        start = [mean(testdata) std(testdata)];
        try
            [phat,pci] = mle(testdata,'pdf',pdf_truncnorm,'start',start,'lower',[-Inf 0]);
            fprintf('%d\n',lagi);
        catch
            fprintf('%d %s\n',lagi,lasterr);
        end
    end
end

InspectGUI(ndsinter,'addObjs',{shsyinter},'optArgs', ...
    {{'Objects',{{'nptgroup',{'GroupEvent','Object',{'adjspikes',{'Fast'}}}, ...
                        {'GetClusterDirs'}}}}, ...
     {'SurrHist'}}, ...
    'SP',[2 1],'LinkedZoom',1)
InspectGUI(shsy,'addObjs',{shsy},'optArgs', ...
    {{'Rasters','Interleaved','Fast'}, ...
        {'SurrHist'}}, ...
    'SP',[2 1],'LinkedZoom',1)
InspectGUI(ndintra,'Overplot','Objects',{{'shufflesync',{'XCorr','NormTest','jbtest','ColorBar','CLim',[0 50]}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','NormTest','jbtest'},{'ResultFile','shsyresultA.mat','SurrData','shsysdataA.mat'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','NormTest','jbtest'},{'ResultFile','shsyresultB.mat','SurrData','shsysdataB.mat'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','NormTest','jbtest'},{'ResultFile','shsyresultC.mat','SurrData','shsysdataC.mat'}}})
InspectGUI(ndshsy,'Objects', ...
    {{'shufflesync',{'Rasters','Fast','Interleaved'}}; ...
     {'nptgroup',{'Object',{'firingrate',{'PSTH'},{'Repetitions','Rate','Binsize',1,'redo'}}}, ...
		{'GetClusterDirs'}}; ...
     {'shufflesync',{'XCorr'}}; ...
     {'shufflesync',{'XCorr'},{'SurrData','shsysdataA.mat','ResultFile','shsyresultA.mat'}}; ...
     {'shufflesync',{'XCorr'},{'SurrData','shsysdataB.mat','ResultFile','shsyresultB.mat'}}; ...
     {'shufflesync',{'XCorr'},{'SurrData','shsysdataC.mat','ResultFile','shsyresultC.mat'}}}, ...
 'SP',[6 1],'LinkedZoom',1)
InspectGUI(ndshsy,'addObjs',{ndshsy},'optArgs', ...
    {{'Objects',{{'shufflesync',{'Rasters','Fast','Interleaved'}}}}, ...
     {'Overplot','Objects',{{'shufflesync',{'XCorr'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData'},{'ResultFile','shsyresultA.mat','SurrData','shsysdataA.mat'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData'},{'ResultFile','shsyresultB.mat','SurrData','shsysdataB.mat'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData'},{'ResultFile','shsyresultC.mat','SurrData','shsysdataC.mat'}}}}},'SP',[2 1],'LinkedZoom',1)
InspectGUI(ndshsy,'addObjs',{ndshsy,ndshsy,ndshsy,ndshsy,ndshsy},'optArgs', ...
    {{'Objects',{{'shufflesync',{'Rasters','Fast','Interleaved'}}}}, ...
     {'Overplot','Objects',{{'shufflesync',{'XCorr'}}; ...
                 {'shufflesync',{'XCorr','NoXCorrData'},{'ResultFile','shsyresultA.mat','SurrData','shsysdataA.mat'}}; ...
                 {'shufflesync',{'XCorr','NoXCorrData'},{'ResultFile','shsyresultB.mat','SurrData','shsysdataB.mat'}}; ...
                 {'shufflesync',{'XCorr','NoXCorrData'},{'ResultFile','shsyresultC.mat','SurrData','shsysdataC.mat'}}}}, ...
     {'Objects',{{'shufflesync',{'PSTH'}}}}, ...
     {'Objects',{{'shufflesync',{'PSTH'},{'ResultFile','shsyresultA.mat','SurrData','shsysdataA.mat'}}}}, ...
     {'Objects',{{'shufflesync',{'PSTH'},{'ResultFile','shsyresultB.mat','SurrData','shsysdataB.mat'}}}}, ...
     {'Objects',{{'shufflesync',{'PSTH'},{'ResultFile','shsyresultC.mat','SurrData','shsysdataC.mat'}}}}},'SP',[6 1],'LinkedZoom',1)
InspectGUI(ndshsy,'addObjs',{ndshsy},'optArgs', ...
    {{'Objects',{{'shufflesync',{'Rasters','Fast','Interleaved'}}}}, ...
     {'Objects',{{'shufflesync',{'PSTH'}}}}},'SP',[2 1],'LinkedZoom',1)
InspectGUI(ndshsy,'addObjs',{ndshsy},'optArgs', ...
    {{'Objects',{{'shufflesync',{'Rasters','Fast','Interleaved'}}}}, ...
     {'Objects',{{'shufflesync',{'PSTH'},{'ResultFile','shsyresultA.mat','SurrData','shsysdataA.mat'}}}}},'SP',[2 1],'LinkedZoom',1)
InspectGUI(ndshsy,'addObjs',{ndshsy},'optArgs', ...
    {{'Objects',{{'shufflesync',{'Rasters','Fast','Interleaved'}}}}, ...
     {'Objects',{{'shufflesync',{'PSTH'},{'ResultFile','shsyresultB.mat','SurrData','shsysdataB.mat'}}}}},'SP',[2 1],'LinkedZoom',1)
InspectGUI(ndshsy,'addObjs',{ndshsy},'optArgs', ...
    {{'Objects',{{'shufflesync',{'Rasters','Fast','Interleaved'}}}}, ...
     {'Objects',{{'shufflesync',{'PSTH'},{'ResultFile','shsyresultC.mat','SurrData','shsysdataC.mat'}}}}},'SP',[2 1],'LinkedZoom',1)
% highlight synchronous and shift-predictor spikes
InspectGUI(ndintra,'addObjs',{ndintra},'optArgs', ...
    {{'Objects',{{'shufflesync',{'Rasters','Fast','Interleaved'}}}}, ...
     {'Overplot','Objects',{{'shufflesync',{'XCorr','NormTest','jbtest'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','NormTest','jbtest'},{'ResultFile','shsyresultA.mat','SurrData','shsysdataA.mat'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','NormTest','jbtest'},{'ResultFile','shsyresultB.mat','SurrData','shsysdataB.mat'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','NormTest','jbtest'},{'ResultFile','shsyresultC.mat','SurrData','shsysdataC.mat'}}}}},'SP',[2 1],'LinkedZoom',1)
% plot without highlighting spikes
InspectGUI(ndintra,'addObjs',{ndintra},'optArgs', ...
	{{'Objects',{{'nptgroup',{'Object',{'adjspikes',{'Fast','Interleaved'}}}, ...
            {'GetClusterDirs'}}}}; ...
     {'Overplot','Objects',{{'shufflesync',{'XCorr','NormTest','jbtest'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','NormTest','jbtest'},{'DataFile','shsydata.mat','ResultFile','shsyresultA.mat','SurrData','shsysdataA.mat'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','NormTest','jbtest'},{'DataFile','shsydata.mat','ResultFile','shsyresultB.mat','SurrData','shsysdataB.mat'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','NormTest','jbtest'},{'DataFile','shsydata.mat','ResultFile','shsyresultC.mat','SurrData','shsysdataC.mat'}}}}},'SP',[2 1],'LinkedZoom',1)
nd = nptdata('auto');
InspectGUI(nd,'addObjs',{nd,nd},'optArgs', ...
    {{'Objects',{{'shufflesync',{'Rasters','Fast','Interleaved'}}}}, ...
     {'Overplot','Objects',{{'shufflesync',{'XCorr'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData'},{'ResultFile','shsyresultA.mat','SurrData','shsysdataA.mat'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData'},{'ResultFile','shsyresultB.mat','SurrData','shsysdataB.mat'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData'},{'ResultFile','shsyresultC.mat','SurrData','shsysdataC.mat'}}}}, ...
    {'Overplot','Objects',{{'shufflesync',{'XCorr'},{'ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat','DataFile','shsy2data.mat'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData'},{'ResultFile','shsy2resultA.mat','SurrData','shsy2sdataA.mat','DataFile','shsy2data.mat'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData'},{'ResultFile','shsy2resultB.mat','SurrData','shsy2sdataB.mat','DataFile','shsy2data.mat'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData'},{'ResultFile','shsy2resultC.mat','SurrData','shsy2sdataC.mat','DataFile','shsy2data.mat'}}}}},'SP',[3 1],'LinkedZoom',1)
% create nptgroup object to plot spike trains of all responsive cells in a group
ngsite = ProcessDays(nptgroup,'IntraGroup','Cells',ndresp.SessionDirs,'AnalysisLevel','AllIntraGroup');
% create nptgroup object to plot all pairs of responsive cells in a group
ngsitepairs = ProcessDays(nptgroup,'IntraGroup','Cells',ndresp.SessionDirs,'AnalysisLevel','AllPairs');
InspectGUI(ngsite2,'addObjs',{ngsite2,ngsitepairs2},'optArgs', ...
    {{'GroupEvent','Object',{'firingrate',{'PSTH'},{'Repetitions','Rate','Binsize',10,'Overlap',1,'redo'}}},{'GroupEvent','GroupPlotSep','Vertical','Object',{'adjspikes',{'Fast'}}}, ...
     {'GroupEvent','GroupPlotSep','Vertical','Object', ...
         {'nptdata',{'Overplot','Objects',{{'shufflesync',{'XCorr','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth','CLim',[0 111]}, ...
            {'ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surr'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth','CLim',[0 111]}, ...
                    {'ResultFile','shsy2resultA.mat','SurrData','shsy2sdataA.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrA'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth','CLim',[0 111]}, ...
                    {'ResultFile','shsy2resultB.mat','SurrData','shsy2sdataB.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrB'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth','CLim',[0 111]}, ...
                    {'ResultFile','shsy2resultC.mat','SurrData','shsy2sdataC.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrC'}}}}}}}, ...
    'SP',[3 1],'LinkedZoom',1)
InspectGUI(ngsitepairs,'GroupEvent','GroupPlotSep','Vertical','Object', ...
         {'nptdata',{'Overplot','Objects', ...
                 {{'shufflesync',{'XCorr','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
                      {'ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surr'}}; ...
                  {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
                      {'ResultFile','shsy2resultA.mat','SurrData','shsy2sdataA.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrA'}}; ...
                  {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
                      {'ResultFile','shsy2resultB.mat','SurrData','shsy2sdataB.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrB'}}; ...
                  {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
                      {'ResultFile','shsy2resultC.mat','SurrData','shsy2sdataC.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrC'}}}}})
% show xcorr for data and shift-predictor versus distributions from surrogates
% need to specify SurrFilePrefix since the plot function uses
% obj.data.Args.SurrFilePrefix to grab windowed data
shsy = shufflesync('auto','ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surr');
shsyA = shufflesync('auto','ResultFile','shsy2resultA.mat','SurrData','shsy2sdataA.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrA');
shsyB = shufflesync('auto','ResultFile','shsy2resultB.mat','SurrData','shsy2sdataB.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrB');
shsyC = shufflesync('auto','ResultFile','shsy2resultC.mat','SurrData','shsy2sdataC.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrC');
% pan through all windows automatically
for i = 1:1700
	subplot(5,1,1); 
	plot(shsy,i,'Windowed','Rasters','Fast','Interleaved');
	title(num2str(i)); 
	subplot(5,1,2); 
	plot(shsy,i,'Windowed','Xlim',[-35.5 35.5]);
	subplot(5,1,3); 
	plot(shsyA,i,'Windowed','Xlim',[-35.5 35.5]);
	subplot(5,1,4); 
	plot(shsyB,i,'Windowed','Xlim',[-35.5 35.5]);
	subplot(5,1,5); 
	plot(shsyC,i,'Windowed','Xlim',[-35.5 35.5]);
	pause(0.1)
end
% show window by window
InspectGUI(shsy,'addObjs',{shsy,shsyA,shsyB,shsyC},'optArgs', ...
    {{'Windowed','Rasters','Fast','Interleaved'}, ...
        {'Windowed','Xlim',[-35.5 35.5]}, ...
        {'Windowed','Xlim',[-35.5 35.5]}, ...
        {'Windowed','Xlim',[-35.5 35.5]}, ...
        {'Windowed','Xlim',[-35.5 35.5]}},'SP',[5 1])
% multi-pair sites: a1s3n12g4, a2s4n14g3
cd /Users/syen/Documents/ShihCheng/Data/Neural/Cat/newcatdata/a1/site03/session12
nga1 = ProcessCellCombos(nptgroup,'IntraGroup','AnalysisLevel','AllPairs','GroupDirName','group0004','Cells',{'cluster01s','cluster02s','cluster03s'});
cd /Users/syen/Documents/ShihCheng/Data/Neural/Cat/newcatdata/a2/site04/session14
nga2 = ProcessCellCombos(nptgroup,'IntraGroup','AnalysisLevel','AllPairs','GroupDirName','group0003','Cells',{'cluster03s','cluster04s','cluster05s'});
ngsitepairs2 = nga1 + nga2;
InspectGUI(ngsitepairs2,'GroupEvent','GroupPlotSep','Vertical','Object', ...
         {'nptdata',{'Overplot','Objects',{{'shufflesync',{'XCorr','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
            {'ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surr'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
                    {'ResultFile','shsy2resultA.mat','SurrData','shsy2sdataA.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrA'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
                    {'ResultFile','shsy2resultB.mat','SurrData','shsy2sdataB.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrB'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
                    {'ResultFile','shsy2resultC.mat','SurrData','shsy2sdataC.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrC'}}}}})
shsy = shufflesync('auto','DataFile','shsy2data.mat','ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat','SurrFilePrefix','shsy2surr');
shsyA = shufflesync('auto','DataFile','shsy2data.mat','ResultFile','shsy2resultA.mat','SurrData','shsy2sdataA.mat','SurrFilePrefix','shsy2surrA');
shsyB = shufflesync('auto','DataFile','shsy2data.mat','ResultFile','shsy2resultB.mat','SurrData','shsy2sdataB.mat','SurrFilePrefix','shsy2surrB');
shsyC = shufflesync('auto','DataFile','shsy2data.mat','ResultFile','shsy2resultC.mat','SurrData','shsy2sdataC.mat','SurrFilePrefix','shsy2surrC');
InspectGUI(shsy,'addObjs',{shsy,shsy,shsyA,shsyA,shsyB,shsyB,shsyC,shsyC},'optArgs',{{'Windowed','Rasters','Fast','Interleaved'}, ...
        {'Windowed','XLim',[-10.5 10.5]},{'Windowed','PSTH'},{'Windowed','XLim',[-10.5 10.5]},{'Windowed','PSTH'}, ...
        {'Windowed','XLim',[-10.5 10.5]},{'Windowed','PSTH'},{'Windowed','XLim',[-10.5 10.5]},{'Windowed','PSTH'}},'SP',[5 2],'LinkedZoom',1)
InspectGUI(shsy,'addObjs',{shsy,shsyA,shsyA,shsyB,shsyB,shsyC,shsyC},'optArgs',{{'Windowed','XLim',[-10.5 10.5]}, ...
        {'Windowed','PSTH'},{'Windowed','XLim',[-10.5 10.5]},{'Windowed','PSTH'},{'Windowed','XLim',[-10.5 10.5]}, ...
        {'Windowed','PSTH'},{'Windowed','XLim',[-10.5 10.5]},{'Windowed','PSTH'}},'SP',[4 2],'LinkedZoom',1)
InspectGUI(ndintra, ...
    'Overplot','Objects',{{'shufflesync',{'XCorr','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
            {'ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surr'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
                    {'ResultFile','shsy2resultA.mat','SurrData','shsy2sdataA.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrA'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
                    {'ResultFile','shsy2resultB.mat','SurrData','shsy2sdataB.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrB'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
                    {'ResultFile','shsy2resultC.mat','SurrData','shsy2sdataC.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrC'}}})
figure('units','normalized','outerposition',[0 0 1 1],'Color','w'); 
subplot(2,1,1)
plot(shsyC,1,'Windowed','Rasters','Fast','Interleaved');
mov=avifile('winxcorr2','fps',2); 
% for i = 745:794
for i = [286:292 608:616]
    subplot(2,1,1)
    plot(shsyC,i,'Windowed','Rasters','Fast','Interleaved');
    subplot(2,1,2)
    plot(shsyC,i,'Windowed','XLim',[-10.5 10.5],'YLim',[0 30]);
	f2=getframe(gcf); % gets the gcf  
	mov=addframe(mov,f2); % adds the frame into mov  
end
mov=close(mov); % closes the mov 
InspectGUI(shsy,'addObjs',{shsy},'optArgs', ...
    {{'Rasters','Fast','Interleaved'}, ...
        {'XCorr','YLim',[-10 10]}},'SP',[2 1],'LinkedZoom',1)
% 3 panel figure for presentation
figure
h = separateAxis('Vertical',3);
axes('position',h(3,:))
plot(ngsite,12,'GroupEvent','Object',{'firingrate',{'PSTH'},{'Repetitions','Rate'}});
xlabel('')
xlim([3000 11000])
set(gca,'XTick',[])
axes('position',h(2,:))
plot(ngsite,12,'GroupEvent','Object',{'adjspikes',{'Fast','Interleaved'}});
xlabel('')
xlim([3000 11000])
set(gca,'XTick',[])
axes('position',h(1,:))
plot(ngsitepairs,12,'GroupEvent','GroupPlotSep','Vertical','Object', ...
    {'shufflesync',{'XCorr','XCorrDataOnly','YLim',[-10 10],'NoTitle','XLim',[3000 11000],'ColorBar'}, ...
        {'ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat', ...
            'DataFile','shsy2data.mat','SurrFilePrefix','shsy2surr'}});
% xcorr plot for 3 pairs
figure
plot(ngsitepairs,2,'GroupEvent','GroupPlotSep','Vertical','Object', ...
{'nptdata',{'Overplot','Objects',{{'shufflesync',{'XCorr','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth','NoTitle'}, ...
{'ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surr'}}; ...
{'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth','NoTitle'}, ...
{'ResultFile','shsy2resultA.mat','SurrData','shsy2sdataA.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrA'}}; ...
{'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth','NoTitle'}, ...
{'ResultFile','shsy2resultB.mat','SurrData','shsy2sdataB.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrB'}}; ...
{'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth','NoTitle'}, ...
{'ResultFile','shsy2resultC.mat','SurrData','shsy2sdataC.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrC'}}}}})
linkedzoom onx
% summary figures
InspectGUI(ngsitepairs2,'GroupEvent','GroupPlotSep','Vertical','Object', ...
{'nptdata',{'Overplot','Objects',{{'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','NormTest','min','Summary','NoTitle'}, ...
{'ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surr'}}; ...
{'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','NormTest','min','Summary','NoTitle'}, ...
{'ResultFile','shsy2resultA.mat','SurrData','shsy2sdataA.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrA'}}; ...
{'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','NormTest','min','Summary','NoTitle'}, ...
{'ResultFile','shsy2resultB.mat','SurrData','shsy2sdataB.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrB'}}; ...
{'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','NormTest','min','Summary','NoTitle','XLim',[-10.5 10.5],'YLim',[1 9],'CLim',[0 9]}, ...
{'ResultFile','shsy2resultC.mat','SurrData','shsy2sdataC.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrC'}}}}})
% xcorr plot for 3 pairs
figure
plot(ngsitepairs,5,'GroupEvent','GroupPlotSep','Vertical','Object', ...
{'nptdata',{'Overplot','Objects',{{'shufflesync',{'XCorr','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth','NoTitle','XLim',[27400 28200]}, ...
{'ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surr'}}; ...
{'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth','NoTitle','XLim',[27400 28200]}, ...
{'ResultFile','shsy2resultA.mat','SurrData','shsy2sdataA.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrA'}}; ...
{'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth','NoTitle','XLim',[27400 28200]}, ...
{'ResultFile','shsy2resultB.mat','SurrData','shsy2sdataB.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrB'}}; ...
{'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth','NoTitle','XLim',[27400 28200]}, ...
{'ResultFile','shsy2resultC.mat','SurrData','shsy2sdataC.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrC'}}}}})
linkedzoom onx
[ndintra,shsummary] = ProcessDirs(ndintra,'nptDirCmd','load(''shufflesummary''); if(~isempty(shsummary)) ybins = 1:2:9; xbins = -10.5:10.5; [ub,ui,uj] = unique(shsummary(:,[1 2]),''rows'');nsummary = histn(shsummary(ui,[3 1]),concat(ybins'',xbins'',''Columnwise'')); data = [data; repmat(i,5,1) nsummary]; end');
for i = 1:50
    plot(ndinter,i,'Overplot','Objects', ...
        {{'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','NormTest','min','Summary','NoTitle'}, ...
        {'ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surr'}}; ...
        {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','NormTest','min','Summary','NoTitle'}, ...
        {'ResultFile','shsy2resultA.mat','SurrData','shsy2sdataA.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrA'}}; ...
        {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','NormTest','min','Summary','NoTitle'}, ...
        {'ResultFile','shsy2resultB.mat','SurrData','shsy2sdataB.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrB'}}; ...
        {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','NormTest','min','Summary','NoTitle','XLim',[-10.5 10.5],'YLim',[1 9],'CLim',[0 9]}, ...
        {'ResultFile','shsy2resultC.mat','SurrData','shsy2sdataC.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrC'}}});
    beep
    pause(5)
    clf
end
[ndinter,shsummaryinter] = ProcessDirs(ndinter,'nptDirCmd','load(''shufflesummary''); if(~isempty(shsummary)) data = [data; repmat(i,size(shsummary,1),1) shsummary]; end');
shsumdata = shsummary;
% find significant bins within -10 and 10
sigidx = find(abs(shsumdata(:,2))<11);
s1 = shsumdata(sigidx,:);
% find unique windows for each cell
[su,sui,suj] = unique(s1(:,[1 3]),'rows');
% take the diff of both columns so we can toss out false positives e.g.
% window 289 in cell 30, followed by window 290 in cell 31.
ds1 = diff(su);
ds1a = ds1(:,1);
ds1b = ds1(:,2);
[su [ds1; 0 0]]
% check for false positives by
% find rows that have zero in the first column and 1 in the second
falsepos = find(ds1a & (ds1b==1));
if(~isempty(falsepos))
    % change the values in ds1b to non-zero
    ds1b(falsepos) = 500;
end
% find indices not equal to 1, which means these were the breaks between
% consecutive bins
ds2 = find(ds1b~=1);
% find differences in the indices, which gives us the number of consecutive
% bins between the breaks
drnwins = diff(ds2);
if(ds2(1)==1)
    % first bin is a single window epoch so add 1 to durnwins
    drnwins = [1; drnwins];
end
if(ds1(end)==1)
    % last difference is one so we need to add the last group of 
    % consecutive bins to the total
    drnwins = [drnwins; size(su,1) - ds2(end)];
else
    drnwins = [drnwins; 1];    
end

% April 20, 2006
shsy = shufflesync('auto','DataFile','shsy2data.mat','ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat','SurrFilePrefix','shsy2surr');
shsyA = shufflesync('auto','DataFile','shsy2data.mat','ResultFile','shsy2resultA.mat','SurrData','shsy2sdataA.mat','SurrFilePrefix','shsy2surrA');
shsyB = shufflesync('auto','DataFile','shsy2data.mat','ResultFile','shsy2resultB.mat','SurrData','shsy2sdataB.mat','SurrFilePrefix','shsy2surrB');
shsyC = shufflesync('auto','DataFile','shsy2data.mat','ResultFile','shsy2resultC.mat','SurrData','shsy2sdataC.mat','SurrFilePrefix','shsy2surrC');
plot(nptdata('auto'), ...
    'Overplot','Objects',{{'shufflesync',{'XCorr','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
            {'ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surr'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
                    {'ResultFile','shsy2resultA.mat','SurrData','shsy2sdataA.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrA'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
                    {'ResultFile','shsy2resultB.mat','SurrData','shsy2sdataB.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrB'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'NormTest','min','Z3Psth'}, ...
                    {'ResultFile','shsy2resultC.mat','SurrData','shsy2sdataC.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrC'}}});
zoom xon
InspectGUI(shsy,'addObjs',{shsy,shsy,shsyA,shsyA,shsyB,shsyB,shsyC,shsyC},'optArgs',{{'Windowed','Rasters','Fast','Interleaved'}, ...
        {'Windowed'}, ...
        {'Windowed','PSTH'},{'Windowed'},{'Windowed','PSTH'},{'Windowed'}, ...
        {'Windowed','PSTH'},{'Windowed'},{'Windowed','PSTH'}},'SP',[3 3],'LinkedZoom',1)
figure('units','normalized','outerposition',[0 0 1 1],'Color','w'); 
subplot(3,1,1)
plot(shsyC,1,'Windowed','Rasters','Fast','Interleaved');
mov=avifile('winxcorr2','fps',2); 
% for i = 745:794
for i = [286:292 608:616]
    subplot(3,1,1)
    plot(shsyC,i,'Windowed','Rasters','Fast','Interleaved');
    subplot(3,1,2)
    plot(shsyC,i,'Windowed','XLim',[-10.5 10.5],'YLim',[0 30]);
    subplot(3,1,3)
    plot(shsyC,i,'Windowed','PSTH');
	f2=getframe(gcf); % gets the gcf  
	mov=addframe(mov,f2); % adds the frame into mov  
end
mov=close(mov); % closes the mov 

plot(nptdata('auto'), ...
    'Overplot','Objects',{{'shufflesync',{'XCorr','SmoothedPSTH','YLim',[-10 10],'Z3Psth'}, ...
            {'ResultFile','shsy2result.mat','SurrData','shsy2sdata.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surr'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'Z3Psth'}, ...
                    {'ResultFile','shsy2resultA.mat','SurrData','shsy2sdataA.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrA'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'Z3Psth'}, ...
                    {'ResultFile','shsy2resultB.mat','SurrData','shsy2sdataB.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrB'}}; ...
                {'shufflesync',{'XCorr','NoXCorrData','SmoothedPSTH','YLim',[-10 10],'Z3Psth'}, ...
                    {'ResultFile','shsy2resultC.mat','SurrData','shsy2sdataC.mat','DataFile','shsy2data.mat','SurrFilePrefix','shsy2surrC'}}});
